#-----------------------------------------------------------------------------#
# File:     ~.config/yazi/yazi.toml (archlinux @ 'silent')
# Date:     Sat 03 Jan 2026 03:30
# Update:   Sun 04 Jan 2026 22:23
# Owner:    fvb - freekvb@gmail.com - https://freekvb.github.io/fvb/
#-----------------------------------------------------------------------------#


# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 2, 3, 4 ]
sort_by        = "alphabetical"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
#linemode       = "none"
show_hidden    = true
show_symlink   = false
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"


# Subtittles in mpv

[[opener.add-sub]]
run  = ''' printf "sub-add '%%s'\n" %s1 | socat - /tmp/mpv.sock '''
desc = "Add sub to MPV"

[[open.prepend_rules]]
url = "*.{ass,srt,ssa,sty,sup,vtt}"
use = [ "add-sub", "edit" ]
